---
title: "P8105 Homework 6 - UNI: gvs2113"
output: github_document
date: "2023-11-20"
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1 
**Load in the data from github link:** 
```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicide_html = read_csv(url)
```

**Creating a `city_state` variable and performing instructed data cleaning steps.**
```{r}
homicide_df = 
  homicide_html |> 
  mutate(
    city_state = paste(city, state, sep = ", "),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1))|> 
  filter(!(city_state %in% c("Dallas, TX", "Pheonix, AZ", "Kansas City, MO", "Tulsa, AL"))) |> 
  filter(victim_race %in% c("White", "Black")) |> 
  mutate(
    victim_age = replace(victim_age, victim_age == "Unknown", NA),
    victim_age = as.numeric(victim_age)
  )
```

**Baltimore, MD logisitic regression**
```{r}
baltimore = 
  homicide_df |> 
  filter(city_state == "Baltimore, MD")

b_fit = glm(resolution ~ victim_age + victim_sex + victim_race, data = baltimore) |> 
  broom::tidy() |> 
  mutate(
    OR = exp(estimate),
    OR_CI_upper = exp(estimate + 1.96 * std.error),
    OR_CI_lower = exp(estimate - 1.96 * std.error)) |>
  filter(term == "victim_sexMale") |> 
  select(OR, OR_CI_upper, OR_CI_lower) 

b_fit |> 
  knitr::kable(digits = 3)
```

**Logistic Regression for all cities**
```{r}
all_city = 
  homicide_df |> 
  nest(data = -city_state) |> 
  mutate(
    model_map = map(data, \(df) glm(resolution ~ victim_age + victim_sex + victim_race, family = binomial(), data = df)),
    tidy_model = map(model_map, broom::tidy)) |> 
  select( -model_map, -data) |> 
  unnest(cols = tidy_model) |> 
  mutate(
    OR = exp(estimate),
    OR_CI_upper = exp(estimate + 1.96 * std.error),
    OR_CI_lower = exp(estimate - 1.96 * std.error)) |>
  filter(term == "victim_sexMale") |> 
  select(city_state, OR, OR_CI_upper, OR_CI_lower) 

all_city |> 
  head(10) |> 
  knitr::kable(digits = 3)
```

**Plot for OR and CI for each city**
```{r}
all_city |> 
  mutate(city_state = fct_reorder(city_state, OR)) |> 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = OR_CI_lower, ymax = OR_CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Need to add comments

## Problem 2 
**Load in the data:** 
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


## Problem 3
**Load in the data:** 
```{r}
birth_data = read_csv("./data/birthweight.csv") |> 
  janitor::clean_names()
```

